services:
  redis:
    image: redis:7
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  db:
    image: postgres:16
    container_name: trading_bot_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ez_piprazor_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@IkobTek"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  trading_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot
    command: python manage.py runserver 0.0.0.0:4000
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://postgres:%40IkobTek@db:5432/ez_piprazor_db"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot_celery_worker
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://postgres:%40IkobTek@db:5432/ez_piprazor_db"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - trading_bot
    restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot_celery_beat
    command: celery -A config beat --loglevel=info
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://postgres:%40IkobTek@db:5432/ez_piprazor_db"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - trading_bot
    restart: unless-stopped

volumes:
  postgres_data:
